### ISSUE TITLE
Can the component handle its own open state?

### ISSUE THREAD

**Issue by dave-irvine** [danielweinmann/react-native-controlled-picker#1]
Hi again @danielweinmann,

Just wondering if this component could handle its own open state (perhaps with it being overridable)?

It seems a bit unnecessary for me to need to control its open state, especially if I have several on the same screen.

If this is something you'd be happy to have, I could do a PR if you'd rather someone else do the code change?

Thanks!

**Comment by danielweinmann** [comment]
Hey @dave-irvine. I'm against controlled components having a state. Mixing the approaches usually lead to undesired side effects.

But you could create a component (on your project or as a new package) that renders a `react-native-controlled-picker` and controls only the `open` prop via its own internal state.

I'll do something like that for [react-native-stateless-form](https://github.com/danielweinmann/react-native-stateless-form) real soon, enabling `StatelessForm` to "focus" the picker when the user clicks the previous input's keyboard `Next` button and so on.

But this component should have no state in my view and it should be 100% declarative and controlled.
